/**
 * Extra Pakistani home-cooking recipes (~55) merged into the main seed.
 */
export function buildExtraRecipes(R, O, ing, step) {
  const r = (nameEn, nameUr, opts) => ({
    nameEn,
    nameUr,
    imageUrl: '',
    region: opts.region ?? null,
    seasons: opts.seasons || ['all'],
    occasions: (opts.occasions || []).filter(Boolean),
    mealType: opts.mealType || 'lunch',
    prepTimeMinutes: opts.prepTimeMinutes || 40,
    servings: opts.servings || 4,
    tags: opts.tags || [],
    ingredients: opts.ingredients,
    steps: opts.steps,
  });

  return [
    r('Chicken Handi', 'چکن ہانڈی', {
      region: R.punjab, mealType: 'dinner', prepTimeMinutes: 50, tags: ['meat', 'guest-friendly'],
      occasions: [O['guest-visit']],
      ingredients: [ing('Chicken', 'مرغی', 1, 'kg'), ing('Cream', 'کریم', 0.5, 'cup'), ing('Yogurt', 'دہی', 0.5, 'cup'), ing('Tomato', 'ٹماٹر', 3, 'pcs'), ing('Butter', 'مکھن', 2, 'tbsp')],
      steps: [step('Cook chicken with yogurt and spices.', 'مرغی دہی اور مصالحے سے پکائیں۔'), step('Add tomatoes and simmer.', 'ٹماٹر ڈال کر پکائیں۔'), step('Finish with cream and butter.', 'کریم اور مکھن ڈال کر تیار کریں۔')],
    }),
    r('Beef Nihari', 'گائے کی نہاری', {
      region: R.punjab, seasons: ['winter'], mealType: 'breakfast', prepTimeMinutes: 180, tags: ['meat', 'festive'],
      occasions: [O['eid-ul-adha'], O['sehri']],
      ingredients: [ing('Beef shank', 'گائے کا گوشت', 1, 'kg'), ing('Nihari masala', 'نہاری مصالہ', 3, 'tbsp'), ing('Flour', 'آٹا', 2, 'tbsp'), ing('Ginger', 'ادرک', 2, 'tbsp')],
      steps: [step('Slow cook beef with masala for hours.', 'گوشت دھیمی آنچ پر گھنٹوں پکائیں۔'), step('Thicken with flour slurry.', 'آٹے کا گارا ڈالیں۔'), step('Garnish with ginger and serve.', 'ادرک لگا کر پیش کریں۔')],
    }),
    r('Chicken Manchurian', 'چکن منچورین', {
      mealType: 'dinner', prepTimeMinutes: 35, tags: ['meat', 'quick'],
      ingredients: [ing('Chicken', 'مرغی', 0.5, 'kg'), ing('Soy sauce', 'سویا ساس', 2, 'tbsp'), ing('Cornflour', 'کارن فلور', 3, 'tbsp'), ing('Capsicum', 'شملہ مرچ', 1, 'pcs')],
      steps: [step('Coat and fry chicken pieces.', 'مرغی فرائی کریں۔'), step('Make Manchurian sauce.', 'ساس بنائیں۔'), step('Toss chicken in sauce.', 'مرغی ساس میں مکس کریں۔')],
    }),
    r('White Chicken Karahi', 'سفید چکن کڑاہی', {
      region: R.punjab, mealType: 'lunch', prepTimeMinutes: 40, tags: ['meat', 'guest-friendly'],
      occasions: [O['guest-visit']],
      ingredients: [ing('Chicken', 'مرغی', 1, 'kg'), ing('Yogurt', 'دہی', 1, 'cup'), ing('Green chilies', 'ہری مرچ', 6, 'pcs'), ing('Cream', 'کریم', 0.25, 'cup')],
      steps: [step('Cook chicken in yogurt base.', 'دہی میں مرغی پکائیں۔'), step('Add green chilies and cream.', 'ہری مرچ اور کریم ڈالیں۔'), step('Cook until thick and white.', 'گاڑھا ہونے تک پکائیں۔')],
    }),
    r('Mutton Karahi', 'مٹن کڑاہی', {
      region: R.kpk, mealType: 'dinner', prepTimeMinutes: 70, tags: ['meat', 'guest-friendly', 'festive'],
      occasions: [O['eid-ul-adha'], O['guest-visit']],
      ingredients: [ing('Mutton', 'بکرے کا گوشت', 1, 'kg'), ing('Tomatoes', 'ٹماٹر', 5, 'pcs'), ing('Ginger garlic', 'ادرک لہسن', 2, 'tbsp'), ing('Green chilies', 'ہری مرچ', 5, 'pcs')],
      steps: [step('Braise mutton until tender.', 'گوشت نرم ہونے تک پکائیں۔'), step('Add tomatoes on high heat.', 'تیز آنچ پر ٹماٹر ڈالیں۔'), step('Finish with green chilies.', 'ہری مرچ ڈال کر تیار کریں۔')],
    }),
    r('Chicken Tikka Masala', 'چکن تکہ مصالحہ', {
      mealType: 'dinner', prepTimeMinutes: 55, tags: ['meat', 'guest-friendly'],
      occasions: [O.wedding, O['guest-visit']],
      ingredients: [ing('Chicken', 'مرغی', 0.75, 'kg'), ing('Yogurt', 'دہی', 0.5, 'cup'), ing('Tomato puree', 'ٹماٹر پیوری', 1, 'cup'), ing('Cream', 'کریم', 0.5, 'cup')],
      steps: [step('Marinate and grill chicken tikka.', 'چکن تکہ میرینیٹ کر کے گرل کریں۔'), step('Cook creamy tomato gravy.', 'کریمی گریوی بنائیں۔'), step('Combine and simmer.', 'ملا کر دم دیں۔')],
    }),
    r('Kofta Curry', 'کوفتہ', {
      region: R.punjab, mealType: 'lunch', prepTimeMinutes: 60, tags: ['meat'],
      ingredients: [ing('Minced meat', 'قیمہ', 0.5, 'kg'), ing('Onion', 'پیاز', 2, 'pcs'), ing('Gram flour', 'بیسن', 2, 'tbsp'), ing('Yogurt', 'دہی', 0.5, 'cup')],
      steps: [step('Shape spiced koftas.', 'کوفتے بنائیں۔'), step('Make onion gravy.', 'گریوی بنائیں۔'), step('Simmer koftas in gravy.', 'کوفتے گریوی میں پکائیں۔')],
    }),
    r('Dum Pukht', 'دم پخت', {
      region: R.kpk, mealType: 'dinner', prepTimeMinutes: 120, tags: ['meat', 'festive', 'guest-friendly'],
      occasions: [O.wedding, O['guest-visit']],
      ingredients: [ing('Mutton', 'گوشت', 1, 'kg'), ing('Yogurt', 'دہی', 1, 'cup'), ing('Whole spices', 'کھڑے مصالحے', 2, 'tbsp'), ing('Oil', 'تیل', 0.5, 'cup')],
      steps: [step('Seal pot with dough.', 'دیگ کو آٹے سے بند کریں۔'), step('Slow cook on dum.', 'دم پر پکائیں۔'), step('Open and serve fragrant meat.', 'کھول کر پیش کریں۔')],
    }),
    r('Chicken Malai Boti', 'چکن ملائی بوٹی', {
      mealType: 'dinner', prepTimeMinutes: 45, tags: ['meat', 'guest-friendly', 'quick'],
      occasions: [O['guest-visit'], O.birthday],
      ingredients: [ing('Chicken', 'مرغی', 0.75, 'kg'), ing('Cream', 'کریم', 0.5, 'cup'), ing('Cheese', 'پنیر', 2, 'tbsp'), ing('Yogurt', 'دہی', 0.25, 'cup')],
      steps: [step('Marinate in cream and cheese.', 'کریم اور پنیر میں میرینیٹ کریں۔'), step('Skewer and grill.', 'سیکھ پر گرل کریں۔'), step('Serve with chutney.', 'چٹنی کے ساتھ دیں۔')],
    }),
    r('Beef Biryani', 'گائے کی بریانی', {
      region: R.sindh, mealType: 'lunch', prepTimeMinutes: 100, tags: ['meat', 'festive', 'guest-friendly'],
      occasions: [O['eid-ul-fitr'], O.wedding],
      ingredients: [ing('Beef', 'گائے کا گوشت', 0.75, 'kg'), ing('Basmati rice', 'چاول', 0.5, 'kg'), ing('Yogurt', 'دہی', 1, 'cup'), ing('Biryani masala', 'بریانی مصالہ', 3, 'tbsp')],
      steps: [step('Cook beef masala.', 'گوشت کا مصالحہ پکائیں۔'), step('Parboil rice.', 'چاول ابل لیں۔'), step('Layer and dum cook.', 'تہیں لگا کر دم دیں۔')],
    }),
    r('Vegetable Biryani', 'سبزی بریانی', {
      mealType: 'lunch', prepTimeMinutes: 55, tags: ['veg', 'festive'],
      occasions: [O.birthday, O['guest-visit']],
      ingredients: [ing('Mixed vegetables', 'سبزیاں', 0.5, 'kg'), ing('Basmati rice', 'چاول', 0.5, 'kg'), ing('Yogurt', 'دہی', 0.5, 'cup'), ing('Biryani masala', 'مصالحہ', 2, 'tbsp')],
      steps: [step('Cook spiced vegetables.', 'سبزیاں مصالحے سے پکائیں۔'), step('Layer with rice.', 'چاول کی تہ لگائیں۔'), step('Dum for 15 minutes.', '۱۵ منٹ دم دیں۔')],
    }),
    r('Chana Masala', 'چنے مصالے دار', {
      region: R.punjab, mealType: 'breakfast', prepTimeMinutes: 35, tags: ['veg', 'quick'],
      occasions: [O['sehri'], O.basant],
      ingredients: [ing('Chickpeas', 'چنے', 2, 'cup'), ing('Onion', 'پیاز', 2, 'pcs'), ing('Tomato', 'ٹماٹر', 2, 'pcs'), ing('Chana masala', 'مصالحہ', 2, 'tbsp')],
      steps: [step('Boil chickpeas soft.', 'چنے ابالیں۔'), step('Make onion tomato masala.', 'پیاز ٹماٹر بھونیں۔'), step('Simmer together.', 'ملا کر پکائیں۔')],
    }),
    r('Aloo Keema', 'آلو قیمہ', {
      region: R.punjab, mealType: 'lunch', prepTimeMinutes: 40, tags: ['meat'],
      ingredients: [ing('Minced meat', 'قیمہ', 0.5, 'kg'), ing('Potatoes', 'آلو', 3, 'pcs'), ing('Onion', 'پیاز', 2, 'pcs'), ing('Tomato', 'ٹماٹر', 2, 'pcs')],
      steps: [step('Brown keema with onions.', 'قیمہ بھونیں۔'), step('Add potatoes and tomatoes.', 'آلو اور ٹماٹر ڈالیں۔'), step('Cook until potatoes soften.', 'آلو نرم ہونے تک پکائیں۔')],
    }),
    r('Methi Chicken', 'میتھی چکن', {
      seasons: ['winter'], mealType: 'lunch', prepTimeMinutes: 45, tags: ['meat'],
      ingredients: [ing('Chicken', 'مرغی', 0.75, 'kg'), ing('Fenugreek leaves', 'میتھی', 1, 'bunch'), ing('Yogurt', 'دہی', 0.5, 'cup'), ing('Onion', 'پیاز', 2, 'pcs')],
      steps: [step('Cook chicken with onions.', 'پیاز میں مرغی پکائیں۔'), step('Add methi and yogurt.', 'میتھی اور دہی ڈالیں۔'), step('Simmer until fragrant.', 'خوشبو آنے تک پکائیں۔')],
    }),
    r('Palak Paneer', 'پالک پنیر', {
      mealType: 'lunch', prepTimeMinutes: 35, tags: ['veg', 'quick'],
      ingredients: [ing('Spinach', 'پالک', 0.5, 'kg'), ing('Paneer', 'پنیر', 0.25, 'kg'), ing('Onion', 'پیاز', 1, 'pcs'), ing('Cream', 'کریم', 0.25, 'cup')],
      steps: [step('Blanch and blend spinach.', 'پالک ابال کر پیس لیں۔'), step('Cook with spices.', 'مصالحے سے پکائیں۔'), step('Add paneer cubes.', 'پنیر ڈال دیں۔')],
    }),
    r('Baingan Bharta', 'بینگن بھرتا', {
      region: R.punjab, seasons: ['summer', 'monsoon'], mealType: 'lunch', prepTimeMinutes: 40, tags: ['veg'],
      ingredients: [ing('Eggplant', 'بینگن', 2, 'pcs'), ing('Onion', 'پیاز', 2, 'pcs'), ing('Tomato', 'ٹماٹر', 2, 'pcs'), ing('Green chili', 'ہری مرچ', 2, 'pcs')],
      steps: [step('Roast eggplant and mash.', 'بینگن بھون کر میش کریں۔'), step('Cook onion tomato base.', 'پیاز ٹماٹر بھونیں۔'), step('Mix and simmer.', 'ملا کر پکائیں۔')],
    }),
    r('Okra Masala', 'بھنڈی مصالحہ', {
      seasons: ['summer'], mealType: 'lunch', prepTimeMinutes: 30, tags: ['veg', 'quick'],
      ingredients: [ing('Okra', 'بھنڈی', 0.5, 'kg'), ing('Onion', 'پیاز', 2, 'pcs'), ing('Tomato', 'ٹماٹر', 2, 'pcs'), ing('Spices', 'مصالحہ', 1, 'tbsp')],
      steps: [step('Fry okra lightly.', 'بھنڈی ہلکی فرائی کریں۔'), step('Add onion and tomato.', 'پیاز ٹماٹر ڈالیں۔'), step('Cook until tender.', 'نرم ہونے تک پکائیں۔')],
    }),
    r('Tinda Masala', 'ٹینڈے', {
      seasons: ['summer'], mealType: 'lunch', prepTimeMinutes: 30, tags: ['veg', 'quick'],
      ingredients: [ing('Apple gourd', 'ٹینڈے', 0.5, 'kg'), ing('Onion', 'پیاز', 1, 'pcs'), ing('Tomato', 'ٹماٹر', 2, 'pcs'), ing('Cumin', 'زیرہ', 1, 'tsp')],
      steps: [step('Sauté onion and spices.', 'پیاز بھونیں۔'), step('Add tinda and tomatoes.', 'ٹینڈے اور ٹماٹر ڈالیں۔'), step('Cover and cook soft.', 'دم دے کر پکائیں۔')],
    }),
    r('Kaddu Salan', 'کدو کا سالن', {
      seasons: ['winter'], mealType: 'lunch', prepTimeMinutes: 35, tags: ['veg'],
      ingredients: [ing('Pumpkin', 'کدو', 0.75, 'kg'), ing('Onion', 'پیاز', 1, 'pcs'), ing('Tomato', 'ٹماٹر', 1, 'pcs'), ing('Turmeric', 'ہلدی', 0.5, 'tsp')],
      steps: [step('Cook onion base.', 'پیاز بھونیں۔'), step('Add pumpkin cubes.', 'کدو ڈالیں۔'), step('Simmer until soft and sweet.', 'نرم اور میٹھا ہونے تک پکائیں۔')],
    }),
    r('Arvi Gosht', 'اروی گوشت', {
      seasons: ['winter'], mealType: 'lunch', prepTimeMinutes: 55, tags: ['meat'],
      ingredients: [ing('Mutton', 'گوشت', 0.5, 'kg'), ing('Taro root', 'اروی', 0.5, 'kg'), ing('Onion', 'پیاز', 2, 'pcs'), ing('Yogurt', 'دہی', 0.5, 'cup')],
      steps: [step('Cook meat tender.', 'گوشت پکائیں۔'), step('Add arvi pieces.', 'اروی ڈالیں۔'), step('Simmer until oil separates.', 'تیل الگ ہونے تک پکائیں۔')],
    }),
    r('Chicken Soup', 'چکن سوپ', {
      seasons: ['winter', 'monsoon'], mealType: 'snack', prepTimeMinutes: 25, tags: ['meat', 'quick'],
      occasions: [O['sehri']],
      ingredients: [ing('Chicken', 'مرغی', 0.3, 'kg'), ing('Cornflour', 'کارن فلور', 2, 'tbsp'), ing('Egg', 'انڈا', 1, 'pcs'), ing('Pepper', 'کالی مرچ', 1, 'tsp')],
      steps: [step('Boil chicken stock.', 'مرغی کا یخنی بنائیں۔'), step('Thicken with cornflour.', 'کارن فلور سے گاڑھا کریں۔'), step('Add egg drop and pepper.', 'انڈا اور مرچ ڈالیں۔')],
    }),
    r('Tomato Soup', 'ٹماٹر سوپ', {
      seasons: ['winter'], mealType: 'snack', prepTimeMinutes: 20, tags: ['veg', 'quick'],
      ingredients: [ing('Tomatoes', 'ٹماٹر', 6, 'pcs'), ing('Onion', 'پیاز', 1, 'pcs'), ing('Cream', 'کریم', 2, 'tbsp'), ing('Pepper', 'کالی مرچ', 0.5, 'tsp')],
      steps: [step('Boil and blend tomatoes.', 'ٹماٹر ابال کر پیس لیں۔'), step('Season and simmer.', 'مصالحہ ڈال کر پکائیں۔'), step('Finish with cream.', 'کریم ملا کر دیں۔')],
    }),
    r('Dahi Bhallay Plate', 'دہی بھللے پلیٹ', {
      seasons: ['summer'], mealType: 'snack', prepTimeMinutes: 40, tags: ['veg'],
      occasions: [O['ramadan-iftar'], O.basant],
      ingredients: [ing('Lentil dumplings', 'بھللے', 8, 'pcs'), ing('Yogurt', 'دہی', 2, 'cup'), ing('Chutney', 'چٹنی', 0.5, 'cup'), ing('Chaat masala', 'چاٹ مصالحہ', 1, 'tsp')],
      steps: [step('Soak bhallay.', 'بھللے بھگو لیں۔'), step('Whip seasoned yogurt.', 'دہی پھینٹیں۔'), step('Top with chutneys and masala.', 'چٹنی اور مصالحہ ڈالیں۔')],
    }),
    r('Papri Chaat', 'پاپڑی چاٹ', {
      seasons: ['summer', 'spring'], mealType: 'snack', prepTimeMinutes: 20, tags: ['veg', 'quick'],
      occasions: [O['ramadan-iftar'], O.birthday],
      ingredients: [ing('Papri', 'پاپڑی', 20, 'pcs'), ing('Boiled potato', 'آلو', 2, 'pcs'), ing('Yogurt', 'دہی', 1, 'cup'), ing('Tamarind chutney', 'امی چٹنی', 0.25, 'cup')],
      steps: [step('Layer papri and potato.', 'پاپڑی اور آلو رکھیں۔'), step('Add yogurt and chutneys.', 'دہی اور چٹنی ڈالیں۔'), step('Sprinkle chaat masala.', 'چاٹ مصالحہ چھڑکیں۔')],
    }),
    r('Gol Gappay', 'گول گپے', {
      seasons: ['summer', 'monsoon'], mealType: 'snack', prepTimeMinutes: 25, tags: ['veg', 'quick'],
      occasions: [O.basant, O.birthday],
      ingredients: [ing('Puris', 'گول گپے', 20, 'pcs'), ing('Chickpeas', 'چنے', 1, 'cup'), ing('Potato', 'آلو', 2, 'pcs'), ing('Spiced water', 'پانی', 3, 'cup')],
      steps: [step('Prepare spicy pani.', 'کھٹا میٹھا پانی بنائیں۔'), step('Fill puris with potato mix.', 'بھر کر تیار کریں۔'), step('Dip and eat immediately.', 'ڈبو کر فوراً کھائیں۔')],
    }),
    r('Beef Kabab Roll', 'بیف کباب رول', {
      mealType: 'snack', prepTimeMinutes: 30, tags: ['meat', 'quick', 'guest-friendly'],
      occasions: [O['guest-visit']],
      ingredients: [ing('Seekh kabab', 'سیخ کباب', 4, 'pcs'), ing('Paratha', 'پراٹھا', 4, 'pcs'), ing('Onion', 'پیاز', 1, 'pcs'), ing('Chutney', 'چٹنی', 0.25, 'cup')],
      steps: [step('Warm parathas.', 'پراٹھے گرم کریں۔'), step('Add kabab and salad.', 'کباب اور سلاد رکھیں۔'), step('Roll tightly and serve.', 'لپیٹ کر دیں۔')],
    }),
    r('Chicken Shawarma', 'چکن شاورما', {
      mealType: 'snack', prepTimeMinutes: 35, tags: ['meat', 'quick'],
      ingredients: [ing('Chicken', 'مرغی', 0.5, 'kg'), ing('Pita bread', 'روٹی', 4, 'pcs'), ing('Garlic sauce', 'لہسن ساس', 0.5, 'cup'), ing('Fries', 'فرائز', 1, 'cup')],
      steps: [step('Cook spiced chicken strips.', 'مرغی پکائیں۔'), step('Warm bread.', 'روٹی گرم کریں۔'), step('Assemble with sauce and fries.', 'ساس اور فرائز سے رول بنائیں۔')],
    }),
    r('Anda Shami', 'انڈہ شامی', {
      mealType: 'breakfast', prepTimeMinutes: 20, tags: ['meat', 'quick'],
      occasions: [O['sehri']],
      ingredients: [ing('Shami kabab', 'شامی کباب', 4, 'pcs'), ing('Eggs', 'انڈے', 4, 'pcs'), ing('Onion', 'پیاز', 1, 'pcs'), ing('Oil', 'تیل', 3, 'tbsp')],
      steps: [step('Fry shami lightly.', 'شامی ہلکی فرائی کریں۔'), step('Pour beaten egg over.', 'انڈا ڈالیں۔'), step('Cook both sides.', 'دونوں طرف سے پکائیں۔')],
    }),
    r('French Toast Desi', 'ڈیسی فرنچ ٹوسٹ', {
      mealType: 'breakfast', prepTimeMinutes: 15, tags: ['veg', 'quick'],
      occasions: [O['sehri']],
      ingredients: [ing('Bread', 'ڈبل روٹی', 4, 'pcs'), ing('Eggs', 'انڈے', 2, 'pcs'), ing('Milk', 'دودھ', 0.5, 'cup'), ing('Sugar', 'چینی', 1, 'tbsp')],
      steps: [step('Dip bread in egg milk mix.', 'روٹی انڈے میں ڈبوئیں۔'), step('Pan fry both sides.', 'توا پر سینکیں۔'), step('Serve with tea.', 'چائے کے ساتھ دیں۔')],
    }),
    r('Halwa Suji', 'سوجی کا حلوہ', {
      mealType: 'dessert', prepTimeMinutes: 25, tags: ['veg', 'quick', 'festive'],
      occasions: [O['eid-ul-fitr'], O['ramadan-iftar']],
      ingredients: [ing('Semolina', 'سوجی', 1, 'cup'), ing('Sugar', 'چینی', 1, 'cup'), ing('Ghee', 'گھی', 0.5, 'cup'), ing('Cardamom', 'الائچی', 4, 'pcs')],
      steps: [step('Roast suji in ghee.', 'سوجی گھی میں بھونیں۔'), step('Add sugar syrup.', 'شربت ڈالیں۔'), step('Cook until leaves sides.', 'تار بننے تک پکائیں۔')],
    }),
    r('Gulab Jamun', 'گلاب جامن', {
      mealType: 'dessert', prepTimeMinutes: 45, tags: ['veg', 'festive', 'guest-friendly'],
      occasions: [O['eid-ul-fitr'], O.wedding, O.birthday],
      ingredients: [ing('Milk powder', 'دودھ پاؤڈر', 1, 'cup'), ing('Flour', 'میدہ', 2, 'tbsp'), ing('Sugar syrup', 'شربت', 2, 'cup'), ing('Cardamom', 'الائچی', 4, 'pcs')],
      steps: [step('Make soft dough balls.', 'گولے بنائیں۔'), step('Fry on low heat.', 'ہلکی آنچ پر فرائی کریں۔'), step('Soak in warm syrup.', 'گرم شربت میں بھگوئیں۔')],
    }),
    r('Ras Malai', 'رس ملائی', {
      mealType: 'dessert', prepTimeMinutes: 60, tags: ['veg', 'festive', 'guest-friendly'],
      occasions: [O.wedding, O['eid-ul-fitr'], O.birthday],
      ingredients: [ing('Milk', 'دودھ', 2, 'liter'), ing('Sugar', 'چینی', 1, 'cup'), ing('Cardamom', 'الائچی', 5, 'pcs'), ing('Saffron', 'زعفران', 1, 'pinch')],
      steps: [step('Make soft paneer discs.', 'چینی بنا لیں۔'), step('Reduce sweet milk.', 'میٹھا دودھ گاڑھا کریں۔'), step('Soak discs in milk.', 'دودھ میں بھگو کر ٹھنڈا کریں۔')],
    }),
    r('Firni', 'فرنی', {
      mealType: 'dessert', prepTimeMinutes: 40, tags: ['veg', 'festive'],
      occasions: [O['ramadan-iftar'], O['eid-ul-fitr']],
      ingredients: [ing('Milk', 'دودھ', 1, 'liter'), ing('Rice flour', 'چاول کا آٹا', 4, 'tbsp'), ing('Sugar', 'چینی', 0.75, 'cup'), ing('Cardamom', 'الائچی', 4, 'pcs')],
      steps: [step('Cook milk with rice flour.', 'دودھ اور آٹا پکائیں۔'), step('Sweeten and flavor.', 'چینی اور الائچی ڈالیں۔'), step('Chill in bowls.', 'پیالوں میں ٹھنڈا کریں۔')],
    }),
    r('Sewaiyan', 'سیویاں', {
      mealType: 'dessert', prepTimeMinutes: 25, tags: ['veg', 'quick', 'festive'],
      occasions: [O['eid-ul-fitr']],
      ingredients: [ing('Vermicelli', 'سیویاں', 1, 'cup'), ing('Milk', 'دودھ', 1, 'liter'), ing('Sugar', 'چینی', 0.75, 'cup'), ing('Nuts', 'میوے', 0.25, 'cup')],
      steps: [step('Roast sewaiyan.', 'سیویاں بھونیں۔'), step('Add milk and sugar.', 'دودھ اور چینی ڈالیں۔'), step('Cook soft and garnish.', 'نرم پکا کر میوے ڈالیں۔')],
    }),
    r('Mango Lassi', 'آم لاسی', {
      seasons: ['summer'], mealType: 'drink', prepTimeMinutes: 10, tags: ['veg', 'quick'],
      ingredients: [ing('Mango pulp', 'آم', 1, 'cup'), ing('Yogurt', 'دہی', 1.5, 'cup'), ing('Sugar', 'چینی', 2, 'tbsp'), ing('Ice', 'برف', 0.5, 'cup')],
      steps: [step('Blend mango and yogurt.', 'آم اور دہی بلینڈ کریں۔'), step('Add sugar and ice.', 'چینی اور برف ڈالیں۔'), step('Serve chilled.', 'ٹھنڈی پیش کریں۔')],
    }),
    r('Rooh Afza Milk', 'روح افزا دودھ', {
      seasons: ['summer'], mealType: 'drink', prepTimeMinutes: 5, tags: ['veg', 'quick'],
      occasions: [O['ramadan-iftar'], O['sehri']],
      ingredients: [ing('Milk', 'دودھ', 2, 'cup'), ing('Rooh Afza', 'روح افزا', 3, 'tbsp'), ing('Ice', 'برف', 0.5, 'cup'), ing('Sugar', 'چینی', 1, 'tbsp')],
      steps: [step('Mix Rooh Afza in cold milk.', 'دودھ میں روح افزا ملائیں۔'), step('Add ice.', 'برف ڈالیں۔'), step('Serve immediately.', 'فوراً پیش کریں۔')],
    }),
    r('Kashmiri Kahwa', 'کشمیری کہوا', {
      region: R['azad-kashmir'], seasons: ['winter'], mealType: 'drink', prepTimeMinutes: 15, tags: ['veg', 'quick'],
      ingredients: [ing('Green tea', 'سبز چائے', 1, 'tbsp'), ing('Cardamom', 'الائچی', 3, 'pcs'), ing('Saffron', 'زعفران', 1, 'pinch'), ing('Almonds', 'بادام', 6, 'pcs')],
      steps: [step('Boil water with spices.', 'پانی مصالحے سے ابالیں۔'), step('Steep green tea.', 'چائے ڈال کر دم دیں۔'), step('Serve with almonds.', 'بادام کے ساتھ دیں۔')],
    }),
    r('Doodh Patti Special', 'دودھ پتی اسپیشل', {
      mealType: 'drink', prepTimeMinutes: 10, tags: ['veg', 'quick'],
      ingredients: [ing('Milk', 'دودھ', 2, 'cup'), ing('Tea leaves', 'چائے', 2, 'tsp'), ing('Sugar', 'چینی', 2, 'tsp'), ing('Cardamom', 'الائچی', 2, 'pcs')],
      steps: [step('Boil milk with tea.', 'دودھ اور چائے ابالیں۔'), step('Add sugar and cardamom.', 'چینی اور الائچی ڈالیں۔'), step('Strain and serve hot.', 'چھان کر گرم دیں۔')],
    }),
    r('Chicken Corn Soup', 'چکن کارن سوپ', {
      seasons: ['winter', 'monsoon'], mealType: 'snack', prepTimeMinutes: 25, tags: ['meat', 'quick'],
      ingredients: [ing('Chicken', 'مرغی', 0.25, 'kg'), ing('Sweet corn', 'مکئی', 1, 'cup'), ing('Egg', 'انڈا', 1, 'pcs'), ing('Cornflour', 'کارن فلور', 2, 'tbsp')],
      steps: [step('Boil chicken and corn.', 'مرغی اور مکئی ابالیں۔'), step('Thicken soup.', 'گاڑھا کریں۔'), step('Add egg ribbons.', 'انڈا ڈال کر مکس کریں۔')],
    }),
    r('Beef Pulao', 'بیف پلاؤ', {
      region: R.punjab, mealType: 'lunch', prepTimeMinutes: 80, tags: ['meat', 'guest-friendly'],
      occasions: [O['guest-visit'], O['eid-ul-adha']],
      ingredients: [ing('Beef', 'گوشت', 0.75, 'kg'), ing('Rice', 'چاول', 0.5, 'kg'), ing('Onion', 'پیاز', 2, 'pcs'), ing('Whole spices', 'کھڑے مصالحے', 2, 'tbsp')],
      steps: [step('Make yakhni with beef.', 'گوشت کی یخنی بنائیں۔'), step('Fry onions and add rice.', 'پیاز بھون کر چاول ڈالیں۔'), step('Cook until rice done.', 'چاول پکنے تک دم دیں۔')],
    }),
    r('Yakhni Pulao', 'یخنی پلاؤ', {
      region: R.kpk, mealType: 'lunch', prepTimeMinutes: 75, tags: ['meat', 'guest-friendly'],
      occasions: [O['guest-visit']],
      ingredients: [ing('Mutton', 'گوشت', 0.75, 'kg'), ing('Rice', 'چاول', 0.5, 'kg'), ing('Yogurt', 'دہی', 0.5, 'cup'), ing('Whole spices', 'مصالحہ', 2, 'tbsp')],
      steps: [step('Prepare aromatic stock.', 'خوشبودار یخنی بنائیں۔'), step('Cook rice in stock.', 'یخنی میں چاول پکائیں۔'), step('Rest and fluff.', 'دم دے کر ہلکا مکس کریں۔')],
    }),
    r('Kabuli Pulao', 'کابلی پلاؤ', {
      region: R.kpk, mealType: 'dinner', prepTimeMinutes: 90, tags: ['meat', 'festive', 'guest-friendly'],
      occasions: [O.wedding, O['guest-visit']],
      ingredients: [ing('Mutton', 'گوشت', 1, 'kg'), ing('Rice', 'چاول', 0.5, 'kg'), ing('Carrots', 'گاجر', 2, 'pcs'), ing('Raisins', 'کشمش', 0.25, 'cup')],
      steps: [step('Cook meat tender.', 'گوشت پکائیں۔'), step('Sweet-fry carrots and raisins.', 'گاجر کشمش بھونیں۔'), step('Steam rice with toppings.', 'چاول دم دے کر ٹاپنگ ڈالیں۔')],
    }),
    r('Daal Mash', 'دال ماش', {
      region: R.punjab, mealType: 'lunch', prepTimeMinutes: 35, tags: ['veg'],
      ingredients: [ing('Urad dal', 'ماش کی دال', 1, 'cup'), ing('Onion', 'پیاز', 1, 'pcs'), ing('Tomato', 'ٹماٹر', 1, 'pcs'), ing('Garlic', 'لہسن', 4, 'pcs')],
      steps: [step('Boil dal soft.', 'دال ابالیں۔'), step('Prepare tadka.', 'تڑکہ لگائیں۔'), step('Mix and simmer.', 'ملا کر پکائیں۔')],
    }),
    r('Daal Chana', 'چنے کی دال', {
      mealType: 'lunch', prepTimeMinutes: 40, tags: ['veg'],
      ingredients: [ing('Split chickpeas', 'چنے کی دال', 1, 'cup'), ing('Onion', 'پیاز', 1, 'pcs'), ing('Ginger', 'ادرک', 1, 'tbsp'), ing('Green chili', 'ہری مرچ', 2, 'pcs')],
      steps: [step('Pressure cook dal.', 'دال پکائیں۔'), step('Add tadka.', 'تڑکہ دیں۔'), step('Simmer thick.', 'گاڑھی ہونے تک پکائیں۔')],
    }),
    r('Khichdi', 'کھچڑی', {
      seasons: ['monsoon', 'winter'], mealType: 'dinner', prepTimeMinutes: 30, tags: ['veg', 'quick'],
      occasions: [O['sehri']],
      ingredients: [ing('Rice', 'چاول', 1, 'cup'), ing('Moong dal', 'مونگ دال', 0.5, 'cup'), ing('Turmeric', 'ہلدی', 0.5, 'tsp'), ing('Ghee', 'گھی', 2, 'tbsp')],
      steps: [step('Wash rice and dal.', 'چاول دال دھو لیں۔'), step('Cook soft with turmeric.', 'ہلدی سے نرم پکائیں۔'), step('Finish with ghee tadka.', 'گھی کا تڑکہ لگائیں۔')],
    }),
    r('Chicken Roast', 'چکن روسٹ', {
      mealType: 'dinner', prepTimeMinutes: 70, tags: ['meat', 'guest-friendly', 'festive'],
      occasions: [O.birthday, O['guest-visit'], O.wedding],
      ingredients: [ing('Whole chicken', 'پوری مرغی', 1, 'pcs'), ing('Yogurt', 'دہی', 1, 'cup'), ing('Roast masala', 'روسٹ مصالحہ', 3, 'tbsp'), ing('Butter', 'مکھن', 3, 'tbsp')],
      steps: [step('Marinate chicken overnight if possible.', 'مرغی میرینیٹ کریں۔'), step('Roast until golden.', 'سنہری ہونے تک بیک/روسٹ کریں۔'), step('Baste with butter.', 'مکھن لگا کر پیش کریں۔')],
    }),
    r('Fish Fry', 'مچھلی فرائی', {
      region: R.sindh, seasons: ['winter'], mealType: 'dinner', prepTimeMinutes: 30, tags: ['meat', 'quick'],
      ingredients: [ing('Fish fillets', 'مچھلی', 0.75, 'kg'), ing('Gram flour', 'بیسن', 0.5, 'cup'), ing('Red chili', 'لال مرچ', 1, 'tsp'), ing('Lemon', 'لیموں', 1, 'pcs')],
      steps: [step('Coat fish in spiced batter.', 'بیسن لگا کر تیار کریں۔'), step('Deep fry crisp.', 'کرسپی فرائی کریں۔'), step('Serve with lemon.', 'لیموں کے ساتھ دیں۔')],
    }),
    r('Prawn Masala', 'جھینگا مصالحہ', {
      region: R.sindh, mealType: 'dinner', prepTimeMinutes: 30, tags: ['meat', 'quick', 'guest-friendly'],
      occasions: [O['guest-visit']],
      ingredients: [ing('Prawns', 'جھینگے', 0.5, 'kg'), ing('Onion', 'پیاز', 2, 'pcs'), ing('Tomato', 'ٹماٹر', 2, 'pcs'), ing('Garlic', 'لہسن', 1, 'tbsp')],
      steps: [step('Sauté onion garlic.', 'پیاز لہسن بھونیں۔'), step('Add prawns and spices.', 'جھینگے اور مصالحہ ڈالیں۔'), step('Cook until just done.', 'جیسے ہی پکیں اتار لیں۔')],
    }),
    r('Chapli Burger', 'چپلی برگر', {
      region: R.kpk, mealType: 'snack', prepTimeMinutes: 25, tags: ['meat', 'quick'],
      ingredients: [ing('Chapli kabab', 'چپلی کباب', 2, 'pcs'), ing('Bun', 'بن', 2, 'pcs'), ing('Onion', 'پیاز', 1, 'pcs'), ing('Chutney', 'چٹنی', 2, 'tbsp')],
      steps: [step('Fry chapli kabab.', 'چپلی فرائی کریں۔'), step('Toast buns.', 'بن سینکیں۔'), step('Assemble burger.', 'برگر جوڑیں۔')],
    }),
    r('Bun Kabab', 'بن کباب', {
      region: R.sindh, mealType: 'snack', prepTimeMinutes: 20, tags: ['meat', 'quick'],
      ingredients: [ing('Shami kabab', 'شامی', 2, 'pcs'), ing('Bun', 'بن', 2, 'pcs'), ing('Egg', 'انڈا', 1, 'pcs'), ing('Chutney', 'کٹلپ', 2, 'tbsp')],
      steps: [step('Fry kabab and egg.', 'کباب اور انڈا فرائی کریں۔'), step('Fill soft bun.', 'بن میں بھریں۔'), step('Add chutney and serve.', 'کٹلپ لگا کر دیں۔')],
    }),
    r('Naan Chany', 'نان چنے', {
      region: R.punjab, mealType: 'breakfast', prepTimeMinutes: 30, tags: ['veg'],
      occasions: [O['sehri']],
      ingredients: [ing('Chickpeas', 'چنے', 2, 'cup'), ing('Naan', 'نان', 4, 'pcs'), ing('Onion', 'پیاز', 1, 'pcs'), ing('Chaat masala', 'چاٹ مصالحہ', 1, 'tsp')],
      steps: [step('Cook spicy chana.', 'چنے پکائیں۔'), step('Warm naan.', 'نان گرم کریں۔'), step('Serve together.', 'ساتھ پیش کریں۔')],
    }),
    r('Qeema Naan', 'قیمہ نان', {
      mealType: 'dinner', prepTimeMinutes: 40, tags: ['meat', 'guest-friendly'],
      occasions: [O['guest-visit']],
      ingredients: [ing('Minced meat', 'قیمہ', 0.5, 'kg'), ing('Naan dough', 'نان کا آٹا', 4, 'pcs'), ing('Onion', 'پیاز', 1, 'pcs'), ing('Spices', 'مصالحہ', 1, 'tbsp')],
      steps: [step('Cook dry keema filling.', 'قیمہ خشک بھونیں۔'), step('Stuff into naan dough.', 'آٹے میں بھریں۔'), step('Bake or tawa cook.', 'سینک کر تیار کریں۔')],
    }),
    r('Lachha Paratha', 'لچھا پراٹھا', {
      mealType: 'breakfast', prepTimeMinutes: 25, tags: ['veg', 'quick'],
      ingredients: [ing('Flour', 'آٹا', 2, 'cup'), ing('Ghee', 'گھی', 4, 'tbsp'), ing('Salt', 'نمک', 0.5, 'tsp')],
      steps: [step('Knead soft dough.', 'آٹا گوندھیں۔'), step('Layer with ghee and fold.', 'گھی لگا کر تہیں بنائیں۔'), step('Cook flaky on tawa.', 'توا پر کرکرا سینکیں۔')],
    }),
    r('Besan Chilla', 'بیسن چلا', {
      mealType: 'breakfast', prepTimeMinutes: 20, tags: ['veg', 'quick'],
      occasions: [O['sehri']],
      ingredients: [ing('Gram flour', 'بیسن', 1, 'cup'), ing('Onion', 'پیاز', 1, 'pcs'), ing('Tomato', 'ٹماٹر', 1, 'pcs'), ing('Green chili', 'ہری مرچ', 1, 'pcs')],
      steps: [step('Make thin batter.', 'گھول بنائیں۔'), step('Pour on tawa like omelette.', 'توا پر پھیلادیں۔'), step('Cook both sides.', 'دونوں طرف سینکیں۔')],
    }),
    r('Potato Cutlets', 'آلو کٹلٹ', {
      mealType: 'snack', prepTimeMinutes: 30, tags: ['veg', 'quick'],
      occasions: [O['ramadan-iftar']],
      ingredients: [ing('Boiled potatoes', 'آلو', 4, 'pcs'), ing('Breadcrumbs', 'کرمب', 1, 'cup'), ing('Egg', 'انڈا', 1, 'pcs'), ing('Spices', 'مصالحہ', 1, 'tsp')],
      steps: [step('Mash spiced potatoes.', 'آلو میش کریں۔'), step('Shape and coat.', 'شیپ دے کر کوٹ کریں۔'), step('Shallow fry golden.', 'سنہری فرائی کریں۔')],
    }),
    r('Chicken Pakora', 'چکن پکوڑے', {
      seasons: ['monsoon'], mealType: 'snack', prepTimeMinutes: 30, tags: ['meat', 'quick'],
      occasions: [O['ramadan-iftar']],
      ingredients: [ing('Chicken', 'مرغی', 0.4, 'kg'), ing('Gram flour', 'بیسن', 1, 'cup'), ing('Spices', 'مصالحہ', 2, 'tsp'), ing('Oil', 'تیل', 2, 'cup')],
      steps: [step('Batter chicken pieces.', 'بیسن لگا لیں۔'), step('Deep fry crisp.', 'کرسپی فرائی کریں۔'), step('Serve hot with chutney.', 'گرم چٹنی کے ساتھ دیں۔')],
    }),
    r('Imli Chutney Chicken', 'امی چٹنی چکن', {
      mealType: 'dinner', prepTimeMinutes: 40, tags: ['meat'],
      ingredients: [ing('Chicken', 'مرغی', 0.75, 'kg'), ing('Tamarind', 'امی', 3, 'tbsp'), ing('Onion', 'پیاز', 2, 'pcs'), ing('Jaggery', 'گڑ', 1, 'tbsp')],
      steps: [step('Cook chicken with onions.', 'مرغی بھونیں۔'), step('Add tamarind sauce.', 'امی ساس ڈالیں۔'), step('Simmer tangy-sweet.', 'کھٹا میٹھا پکا لیں۔')],
    }),
    r('Achari Gosht', 'اچاری گوشت', {
      region: R.punjab, mealType: 'lunch', prepTimeMinutes: 65, tags: ['meat', 'guest-friendly'],
      occasions: [O['guest-visit']],
      ingredients: [ing('Mutton', 'گوشت', 0.75, 'kg'), ing('Pickle spices', 'اچار مصالحہ', 2, 'tbsp'), ing('Yogurt', 'دہی', 0.5, 'cup'), ing('Mustard oil', 'سرسوں کا تیل', 3, 'tbsp')],
      steps: [step('Bloom achari spices in oil.', 'مصالحہ بھونیں۔'), step('Add meat and yogurt.', 'گوشت اور دہی ڈالیں۔'), step('Cook until tender and tangy.', 'نرم اور تیز ہونے تک پکائیں۔')],
    }),
    r('Sindhi Curry', 'سندھی کری', {
      region: R.sindh, mealType: 'lunch', prepTimeMinutes: 45, tags: ['veg'],
      ingredients: [ing('Gram flour', 'بیسن', 0.5, 'cup'), ing('Mixed vegetables', 'سبزیاں', 0.5, 'kg'), ing('Tamarind', 'امی', 2, 'tbsp'), ing('Curry leaves', 'کڑی پتہ', 8, 'pcs')],
      steps: [step('Make besan curry base.', 'بیسن کری بنائیں۔'), step('Add vegetables.', 'سبزیاں ڈالیں۔'), step('Finish sour with tamarind.', 'امی سے کھٹا کریں۔')],
    }),
    r('Sai Bhaji Rice', 'سائی بھاجی چاول', {
      region: R.sindh, seasons: ['winter'], mealType: 'lunch', prepTimeMinutes: 50, tags: ['veg'],
      ingredients: [ing('Spinach mix', 'ساگ', 0.5, 'kg'), ing('Dal', 'دال', 0.5, 'cup'), ing('Rice', 'چاول', 2, 'cup'), ing('Onion', 'پیاز', 1, 'pcs')],
      steps: [step('Cook sai bhaji soft.', 'سائی بھاجی پکائیں۔'), step('Boil plain rice.', 'چاول ابالیں۔'), step('Serve together.', 'ساتھ پیش کریں۔')],
    }),
    r('Balochi Sajji Platter', 'بلوچی سجی پلیٹر', {
      region: R.balochistan, mealType: 'dinner', prepTimeMinutes: 150, tags: ['meat', 'festive', 'guest-friendly'],
      occasions: [O['eid-ul-adha'], O['guest-visit'], O.wedding],
      ingredients: [ing('Whole lamb leg', 'ران', 1, 'pcs'), ing('Salt', 'نمک', 2, 'tbsp'), ing('Sajji masala', 'سجی مصالحہ', 3, 'tbsp'), ing('Lemon', 'لیموں', 2, 'pcs')],
      steps: [step('Dry rub meat well.', 'مصالحہ لگا کر رگڑیں۔'), step('Roast slowly until cooked through.', 'آہستہ روسٹ کریں۔'), step('Rest and carve.', 'تھوڑا رکھ کر کاٹیں۔')],
    }),
    r('Gilgit Apricot Curry', 'خوبانی سالن', {
      region: R['gilgit-baltistan'], seasons: ['summer'], mealType: 'lunch', prepTimeMinutes: 40, tags: ['meat'],
      ingredients: [ing('Dried apricots', 'خوبانی', 1, 'cup'), ing('Mutton', 'گوشت', 0.5, 'kg'), ing('Onion', 'پیاز', 2, 'pcs'), ing('Oil', 'تیل', 0.25, 'cup')],
      steps: [step('Cook meat soft.', 'گوشت پکائیں۔'), step('Add soaked apricots.', 'بھگوی ہوئی خوبانی ڈالیں۔'), step('Simmer sweet-savory.', 'میٹھا نمکین ہونے تک پکائیں۔')],
    }),
    r('Islamabad BBQ Platter', 'اسلام آباد باربی کیو', {
      region: R.islamabad, mealType: 'dinner', prepTimeMinutes: 50, tags: ['meat', 'guest-friendly', 'festive'],
      occasions: [O['guest-visit'], O.birthday],
      ingredients: [ing('Mixed BBQ meats', 'باربی کیو', 1, 'kg'), ing('Mint chutney', 'پودینہ چٹنی', 0.5, 'cup'), ing('Salad', 'سلاد', 1, 'plate'), ing('Naan', 'نان', 4, 'pcs')],
      steps: [step('Grill marinated meats.', 'گوشت گرل کریں۔'), step('Warm naan.', 'نان گرم کریں۔'), step('Serve platter style.', 'پلیٹر میں پیش کریں۔')],
    }),
    r('Fruit Custard', 'فروٹ کسٹرڈ', {
      seasons: ['summer'], mealType: 'dessert', prepTimeMinutes: 25, tags: ['veg', 'quick', 'guest-friendly'],
      occasions: [O.birthday, O['guest-visit']],
      ingredients: [ing('Milk', 'دودھ', 1, 'liter'), ing('Custard powder', 'کسٹرڈ', 3, 'tbsp'), ing('Sugar', 'چینی', 0.5, 'cup'), ing('Mixed fruit', 'پھل', 2, 'cup')],
      steps: [step('Cook custard thick.', 'کسٹرڈ پکائیں۔'), step('Cool completely.', 'ٹھنڈا کریں۔'), step('Fold in fruit and chill.', 'پھل ملا کر فریج رکھیں۔')],
    }),
    r('Chocolate Banana Shake', 'چاکلیٹ کیلا شیک', {
      seasons: ['summer'], mealType: 'drink', prepTimeMinutes: 8, tags: ['veg', 'quick'],
      ingredients: [ing('Banana', 'کیلا', 2, 'pcs'), ing('Milk', 'دودھ', 2, 'cup'), ing('Chocolate syrup', 'چاکلیٹ', 3, 'tbsp'), ing('Ice cream', 'آئس کریم', 2, 'scoop')],
      steps: [step('Blend banana and milk.', 'بلینڈ کریں۔'), step('Add chocolate and ice cream.', 'چاکلیٹ اور آئس کریم ڈالیں۔'), step('Serve cold.', 'ٹھنڈا پیش کریں۔')],
    }),
    r('Masala Fries', 'مصالحہ فرائز', {
      mealType: 'snack', prepTimeMinutes: 25, tags: ['veg', 'quick'],
      ingredients: [ing('Potatoes', 'آلو', 4, 'pcs'), ing('Chaat masala', 'چاٹ مصالحہ', 1, 'tsp'), ing('Red chili', 'لال مرچ', 0.5, 'tsp'), ing('Oil', 'تیل', 2, 'cup')],
      steps: [step('Cut and soak fries.', 'فرائز کاٹ کر بھگوئیں۔'), step('Fry twice for crisp.', 'دو بار فرائی کریں۔'), step('Toss in masala.', 'مصالحہ لگا کر دیں۔')],
    }),
    r('Egg Bhurji', 'انڈہ بھرجی', {
      mealType: 'breakfast', prepTimeMinutes: 15, tags: ['meat', 'quick'],
      occasions: [O['sehri']],
      ingredients: [ing('Eggs', 'انڈے', 4, 'pcs'), ing('Onion', 'پیاز', 1, 'pcs'), ing('Tomato', 'ٹماٹر', 1, 'pcs'), ing('Green chili', 'ہری مرچ', 2, 'pcs')],
      steps: [step('Sauté onion tomato.', 'پیاز ٹماٹر بھونیں۔'), step('Add beaten eggs.', 'انڈے ڈالیں۔'), step('Scramble soft and serve.', 'ہلکا بھون کر دیں۔')],
    }),
    r('Keema Samosa', 'قیمہ سموسے', {
      mealType: 'snack', prepTimeMinutes: 50, tags: ['meat', 'festive'],
      occasions: [O['ramadan-iftar'], O['eid-ul-fitr']],
      ingredients: [ing('Minced meat', 'قیمہ', 0.4, 'kg'), ing('Samosa sheets', 'پتیاں', 20, 'pcs'), ing('Peas', 'مٹر', 0.5, 'cup'), ing('Oil', 'تیل', 2, 'cup')],
      steps: [step('Cook dry keema filling.', 'قیمہ بھونیں۔'), step('Fill and fold samosas.', 'سموسے بھریں۔'), step('Deep fry golden.', 'سنہری فرائی کریں۔')],
    }),
    r('Vegetable Samosa', 'سبزی سموسے', {
      mealType: 'snack', prepTimeMinutes: 45, tags: ['veg', 'festive'],
      occasions: [O['ramadan-iftar'], O.basant],
      ingredients: [ing('Potato pea filling', 'آلو مٹر', 2, 'cup'), ing('Samosa sheets', 'پتیاں', 20, 'pcs'), ing('Spices', 'مصالحہ', 1, 'tbsp'), ing('Oil', 'تیل', 2, 'cup')],
      steps: [step('Prepare spiced filling.', 'بھرن تیار کریں۔'), step('Shape samosas.', 'سموسے بنائیں۔'), step('Fry until crisp.', 'کرسپی فرائی کریں۔')],
    }),
    r('Chicken Malai Karahi', 'چکن ملائی کڑاہی', {
      mealType: 'dinner', prepTimeMinutes: 45, tags: ['meat', 'guest-friendly'],
      occasions: [O['guest-visit']],
      ingredients: [ing('Chicken', 'مرغی', 1, 'kg'), ing('Cream', 'کریم', 0.75, 'cup'), ing('Green chili', 'ہری مرچ', 6, 'pcs'), ing('Butter', 'مکھن', 2, 'tbsp')],
      steps: [step('Cook chicken white base.', 'سفید مرغی پکائیں۔'), step('Add cream and butter.', 'کریم مکھن ڈالیں۔'), step('Finish with green chilies.', 'ہری مرچ سے تیار کریں۔')],
    }),
    r('Daighi Kheer', 'دیگی کھیر', {
      mealType: 'dessert', prepTimeMinutes: 70, tags: ['veg', 'festive', 'guest-friendly'],
      occasions: [O.wedding, O['eid-ul-fitr']],
      ingredients: [ing('Milk', 'دودھ', 3, 'liter'), ing('Rice', 'چاول', 0.5, 'cup'), ing('Sugar', 'چینی', 1.5, 'cup'), ing('Nuts', 'میوے', 0.5, 'cup')],
      steps: [step('Slow reduce milk with rice.', 'دودھ چاول آہستہ پکائیں۔'), step('Sweeten generously.', 'چینی ڈالیں۔'), step('Garnish with nuts.', 'میوے سجا کر دیں۔')],
    }),
  ];
}
