import { buildExtraRecipes } from './extraRecipes.js';

export const regions = [
  { nameEn: 'Punjab', nameUr: 'پنجاب', slug: 'punjab' },
  { nameEn: 'Sindh', nameUr: 'سندھ', slug: 'sindh' },
  { nameEn: 'KPK', nameUr: 'خیبر پختونخوا', slug: 'kpk' },
  { nameEn: 'Balochistan', nameUr: 'بلوچستان', slug: 'balochistan' },
  { nameEn: 'Gilgit-Baltistan', nameUr: 'گلگت بلتستان', slug: 'gilgit-baltistan' },
  { nameEn: 'Azad Kashmir', nameUr: 'آزاد کشمیر', slug: 'azad-kashmir' },
  { nameEn: 'Islamabad', nameUr: 'اسلام آباد', slug: 'islamabad' },
];

export const occasions = [
  { nameEn: 'Eid ul-Fitr', nameUr: 'عید الفطر', slug: 'eid-ul-fitr', icon: '🌙', type: 'religious' },
  { nameEn: 'Eid ul-Adha', nameUr: 'عید الاضحی', slug: 'eid-ul-adha', icon: '🐑', type: 'religious' },
  { nameEn: 'Ramadan Iftar', nameUr: 'رمضان افطار', slug: 'ramadan-iftar', icon: '🕌', type: 'religious' },
  { nameEn: 'Sehri', nameUr: 'سحری', slug: 'sehri', icon: '🌅', type: 'religious' },
  { nameEn: 'Basant', nameUr: 'بasant', slug: 'basant', icon: '🪁', type: 'festival' },
  { nameEn: 'Muharram', nameUr: 'محرم', slug: 'muharram', icon: '🕯️', type: 'religious' },
  { nameEn: 'Wedding', nameUr: 'شادی', slug: 'wedding', icon: '💒', type: 'social' },
  { nameEn: 'Birthday', nameUr: 'سالگرہ', slug: 'birthday', icon: '🎂', type: 'social' },
  { nameEn: 'Guest Visit', nameUr: 'مہمان', slug: 'guest-visit', icon: '👥', type: 'social' },
];

function ing(nameEn, nameUr, quantity, unit) {
  return { nameEn, nameUr, quantity, unit };
}

function step(stepEn, stepUr) {
  return { stepEn, stepUr };
}

export function buildRecipes(regionMap, occasionMap) {
  const R = regionMap;
  const O = occasionMap;

  return [
    {
      nameEn: 'Chicken Karahi', nameUr: 'چکن کڑاہی', imageUrl: 'https://images.unsplash.com/photo-1603894584373-5ac82b2ae398?w=400',
      region: R.punjab, seasons: ['all'], occasions: [O['guest-visit'], O['eid-ul-fitr']],
      mealType: 'lunch', prepTimeMinutes: 45, servings: 4, tags: ['meat', 'guest-friendly'],
      ingredients: [ing('Chicken', 'مرغی', 1, 'kg'), ing('Tomatoes', 'ٹماٹر', 4, 'pcs'), ing('Ginger garlic paste', 'ادرک لہسن', 2, 'tbsp'), ing('Green chilies', 'ہری مرچ', 4, 'pcs'), ing('Oil', 'تیل', 0.25, 'cup')],
      steps: [step('Heat oil and fry chicken until color changes.', 'تیل گرم کریں اور مرغی بھونیں۔'), step('Add ginger garlic paste and tomatoes.', 'ادرک لہسن اور ٹماٹر ڈالیں۔'), step('Cook on high heat until oil separates.', ' tez آنچ پر پکائیں جب تک تیل الگ نہ ہو۔'), step('Add green chilies and serve hot.', 'ہری مرچ ڈال کر گرم پیش کریں۔')],
    },
    {
      nameEn: 'Sindhi Biryani', nameUr: 'سندھی بiryani', imageUrl: 'https://images.unsplash.com/photo-1563379091335-03b21ab4a4f8?w=400',
      region: R.sindh, seasons: ['all'], occasions: [O['eid-ul-fitr'], O.wedding, O.birthday],
      mealType: 'lunch', prepTimeMinutes: 90, servings: 6, tags: ['meat', 'festive', 'guest-friendly'],
      ingredients: [ing('Basmati rice', 'باسmati چاول', 0.5, 'kg'), ing('Mutton', 'بکرے کا گوشت', 0.5, 'kg'), ing('Yogurt', 'دہی', 1, 'cup'), ing('Biryani masala', 'biryani مصالہ', 2, 'tbsp'), ing('Potatoes', 'آلو', 2, 'pcs')],
      steps: [step('Boil rice until 70% done.', 'چاول 70% پکائیں۔'), step('Cook mutton with yogurt and masala.', 'گوشت دہی اور مصالے کے ساتھ پکائیں۔'), step('Layer rice and mutton in pot.', 'برتن میں چاول اور گوشت کی تہیں لگائیں۔'), step('Dum cook for 20 minutes.', '20 منٹ دم دیں۔')],
    },
    {
      nameEn: 'Sarson da Saag', nameUr: 'سرسوں دا ساگ', imageUrl: 'https://images.unsplash.com/photo-1546833999-b9f581a1996d?w=400',
      region: R.punjab, seasons: ['winter'], occasions: [],
      mealType: 'lunch', prepTimeMinutes: 60, servings: 4, tags: ['veg'],
      ingredients: [ing('Mustard leaves', 'سرسوں', 0.5, 'kg'), ing('Spinach', 'پالک', 0.25, 'kg'), ing('Maize flour', 'مکئی کا آٹا', 2, 'tbsp'), ing('Butter', 'مکھن', 2, 'tbsp')],
      steps: [step('Boil mustard leaves and spinach.', 'سرسوں اور پالک ابالیں۔'), step('Grind to coarse paste.', 'موٹا پیسٹ بنائیں۔'), step('Cook with maize flour on low heat.', 'مکئی کے آٹے کے ساتھ دھیمی آنچ پر پکائیں۔'), step('Top with butter and serve with makki roti.', 'مکھن لگا کر مکئی کی روٹی کے ساتھ پیش کریں۔')],
    },
    {
      nameEn: 'Nihari', nameUr: 'نہari', imageUrl: 'https://images.unsplash.com/photo-1585937421612-70a008296fbe?w=400',
      region: R.punjab, seasons: ['winter'], occasions: [O['eid-ul-fitr']],
      mealType: 'breakfast', prepTimeMinutes: 180, servings: 6, tags: ['meat', 'festive'],
      ingredients: [ing('Beef shank', 'گوشت', 1, 'kg'), ing('Nihari masala', 'نہari مصالہ', 3, 'tbsp'), ing('Wheat flour', 'آٹا', 3, 'tbsp'), ing('Ginger', 'ادرک', 1, 'inch')],
      steps: [step('Slow cook beef with nihari masala for 3 hours.', 'گوشت مصالے کے ساتھ 3 گھنٹے پکائیں۔'), step('Make flour slurry and add.', 'آٹے کا مixture ڈالیں۔'), step('Garnish with ginger and serve.', 'ادرک سے سجا کر پیش کریں۔')],
    },
    {
      nameEn: 'Chapli Kebab', nameUr: 'چپلی کباب', imageUrl: 'https://images.unsplash.com/photo-1529042410759-befb1204b468?w=400',
      region: R.kpk, seasons: ['all'], occasions: [O['guest-visit'], O['eid-ul-adha']],
      mealType: 'lunch', prepTimeMinutes: 40, servings: 4, tags: ['meat', 'quick', 'guest-friendly'],
      ingredients: [ing('Minced beef', 'قیمہ', 0.5, 'kg'), ing('Onion', 'پیاز', 1, 'pcs'), ing('Tomato', 'ٹماٹر', 1, 'pcs'), ing('Pomegranate seeds', 'انار دانہ', 1, 'tbsp'), ing('Coriander', 'دھنیا', 2, 'tbsp')],
      steps: [step('Mix all ingredients well.', 'تمام چیزیں اچھی طرح ملا لیں۔'), step('Shape into flat patties.', 'چپٹے کباب بنائیں۔'), step('Shallow fry until cooked.', 'ہلکا تل کر پکائیں۔')],
    },
    {
      nameEn: 'Sajji', nameUr: 'سجی', imageUrl: 'https://images.unsplash.com/photo-1544025162-d76694265947?w=400',
      region: R.balochistan, seasons: ['all'], occasions: [O['guest-visit'], O['eid-ul-adha']],
      mealType: 'dinner', prepTimeMinutes: 120, servings: 4, tags: ['meat', 'guest-friendly'],
      ingredients: [ing('Whole chicken or lamb', 'سارا مرغ/بکرا', 1.5, 'kg'), ing('Salt', 'نمک', 2, 'tbsp'), ing('Black pepper', 'کالی مرچ', 1, 'tsp'), ing('Lemon', 'لیموں', 2, 'pcs')],
      steps: [step('Marinate with salt, pepper and lemon.', 'نمک، کالی مرچ اور لیموں لگائیں۔'), step('Roast on slow fire until tender.', 'دھیمی آگ پر پکائیں۔'), step('Serve with rice or bread.', 'چاول یا روٹی کے ساتھ پیش کریں۔')],
    },
    {
      nameEn: 'Daal Chawal', nameUr: 'دال چاول', imageUrl: 'https://images.unsplash.com/photo-1512058564366-18510be2db19?w=400',
      region: null, seasons: ['all'], occasions: [],
      mealType: 'lunch', prepTimeMinutes: 35, servings: 4, tags: ['veg', 'quick'],
      ingredients: [ing('Masoor daal', 'مسور دال', 1, 'cup'), ing('Rice', 'چاول', 2, 'cup'), ing('Turmeric', 'ہلدی', 0.5, 'tsp'), ing('Cumin', 'زیرہ', 1, 'tsp')],
      steps: [step('Boil daal with turmeric until soft.', 'دال ہلدی کے ساتھ پکائیں۔'), step('Temper with cumin in oil.', 'تیل میں زیرہ بھونیں۔'), step('Cook rice separately and serve.', 'چاول الگ پکا کر ساتھ پیش کریں۔')],
    },
    {
      nameEn: 'Aloo Paratha', nameUr: 'آلو کا paratha', imageUrl: 'https://images.unsplash.com/photo-1601050690597-df0568fa7098?w=400',
      region: null, seasons: ['all'], occasions: [O.sehri],
      mealType: 'breakfast', prepTimeMinutes: 30, servings: 4, tags: ['veg', 'quick'],
      ingredients: [ing('Wheat flour', 'گندم کا آٹا', 2, 'cup'), ing('Potatoes', 'آلو', 3, 'pcs'), ing('Green chilies', 'ہری مرچ', 2, 'pcs'), ing('Butter', 'مکھن', 3, 'tbsp')],
      steps: [step('Boil and mash potatoes with spices.', 'آلو ابال کر مسالے ملا لیں۔'), step('Make dough and stuff with potato mix.', 'آٹا بیلیں اور آلو بھریں۔'), step('Cook on tawa with butter.', 'تاوے پر مکھن لگا کر سیکیں۔')],
    },
    {
      nameEn: 'Pakoras', nameUr: 'پکوڑے', imageUrl: 'https://images.unsplash.com/photo-1606491956689-2ea866880f84?w=400',
      region: null, seasons: ['monsoon', 'winter'], occasions: [O['ramadan-iftar']],
      mealType: 'snack', prepTimeMinutes: 25, servings: 4, tags: ['veg', 'quick'],
      ingredients: [ing('Besan', 'بیسن', 1, 'cup'), ing('Potato', 'آلو', 2, 'pcs'), ing('Onion', 'پیاز', 1, 'pcs'), ing('Red chili powder', 'لال mirch', 1, 'tsp')],
      steps: [step('Make thick besan batter with spices.', 'بیسن گاڑھا گhol بنائیں۔'), step('Dip vegetables in batter.', 'سبزیوں کو گhol میں ڈبوئیں۔'), step('Deep fry until golden.', 'سنہری ہونے تک تلیں۔')],
    },
    {
      nameEn: 'Sheer Khurma', nameUr: 'شیر خرما', imageUrl: 'https://images.unsplash.com/photo-1488477181946-6428a0291777?w=400',
      region: null, seasons: ['all'], occasions: [O['eid-ul-fitr']],
      mealType: 'dessert', prepTimeMinutes: 40, servings: 6, tags: ['veg', 'festive'],
      ingredients: [ing('Vermicelli', 'سیویاں', 1, 'cup'), ing('Milk', 'دودھ', 1, 'litre'), ing('Dates', 'کھجور', 10, 'pcs'), ing('Sugar', 'چینی', 0.5, 'cup'), ing('Almonds', 'بادام', 0.25, 'cup')],
      steps: [step('Boil milk with sugar.', 'دودھ چینی کے ساتھ ابالیں۔'), step('Fry vermicelli in ghee.', 'سیویاں گhee میں بھونیں۔'), step('Add to milk and cook until thick.', 'دودھ میں ڈال کر گاڑھا کریں۔'), step('Garnish with dates and nuts.', 'کھجور اور dry fruits سے سجائیں۔')],
    },
    {
      nameEn: 'Fruit Chaat', nameUr: 'فruit چaat', imageUrl: 'https://images.unsplash.com/photo-1564093497595-5931221260e7?w=400',
      region: null, seasons: ['summer'], occasions: [O['ramadan-iftar']],
      mealType: 'snack', prepTimeMinutes: 15, servings: 4, tags: ['veg', 'quick'],
      ingredients: [ing('Apple', 'سیب', 1, 'pcs'), ing('Banana', 'کیلا', 2, 'pcs'), ing('Orange', 'مالٹا', 2, 'pcs'), ing('Chaat masala', 'chaat مصالہ', 1, 'tsp'), ing('Lemon juice', 'لیموں', 2, 'tbsp')],
      steps: [step('Chop all fruits.', 'تمام fruits کاٹیں۔'), step('Mix with chaat masala and lemon.', 'chaat مصالہ اور لیموں ملا لیں۔'), step('Serve chilled.', 'ٹھنڈا پیش کریں۔')],
    },
    {
      nameEn: 'Dahi Baray', nameUr: 'dahi baray', imageUrl: 'https://images.unsplash.com/photo-1589302168068-964664d93a0b?w=400',
      region: null, seasons: ['summer'], occasions: [O['ramadan-iftar']],
      mealType: 'snack', prepTimeMinutes: 45, servings: 6, tags: ['veg'],
      ingredients: [ing('Urad daal', 'مash دال', 1, 'cup'), ing('Yogurt', 'دہی', 2, 'cup'), ing('Tamarind chutney', 'imli chutney', 0.5, 'cup'), ing('Cumin powder', 'زیرہ', 1, 'tsp')],
      steps: [step('Soak and grind daal to paste.', 'دال بھigo کر پیس لیں۔'), step('Fry small dumplings.', 'چھوٹے پکوڑے تلیں۔'), step('Soak in water, then top with yogurt and chutney.', 'پانی میں بھگوئیں، دہی اور chutney ڈالیں۔')],
    },
    {
      nameEn: 'Gajar ka Halwa', nameUr: 'gajar ka halwa', imageUrl: 'https://images.unsplash.com/photo-1571877227200-a0d98ea607e9?w=400',
      region: R.punjab, seasons: ['winter'], occasions: [O.birthday, O['eid-ul-fitr']],
      mealType: 'dessert', prepTimeMinutes: 50, servings: 6, tags: ['veg', 'festive'],
      ingredients: [ing('Carrots', 'گاجر', 1, 'kg'), ing('Milk', 'دودھ', 1, 'litre'), ing('Sugar', 'چینی', 1, 'cup'), ing('Khoya', 'khoya', 100, 'gram'), ing('Ghee', 'ghee', 4, 'tbsp')],
      steps: [step('Grate carrots and cook in milk.', 'گاجر کدوکش کر دودھ میں پکائیں۔'), step('Add sugar and cook until thick.', 'چینی ڈال کر گاڑھا کریں۔'), step('Add khoya and ghee, cook 10 more minutes.', 'khoya اور ghee ڈال کر 10 منٹ پکائیں۔')],
    },
    {
      nameEn: 'Lassi', nameUr: 'لassi', imageUrl: 'https://images.unsplash.com/photo-1626074353765-517a5e3a7969?w=400',
      region: R.punjab, seasons: ['summer'], occasions: [],
      mealType: 'drink', prepTimeMinutes: 5, servings: 2, tags: ['veg', 'quick'],
      ingredients: [ing('Yogurt', 'دہی', 2, 'cup'), ing('Sugar', 'چینی', 3, 'tbsp'), ing('Ice', 'برف', 1, 'cup'), ing('Water', 'پانی', 0.5, 'cup')],
      steps: [step('Blend yogurt, sugar, water and ice.', 'دہی، چینی، پانی اور برف blend کریں۔'), step('Serve cold in tall glass.', 'ٹھنڈا گلاس میں پیش کریں۔')],
    },
    {
      nameEn: 'Haleem', nameUr: 'haleem', imageUrl: 'https://images.unsplash.com/photo-1585937421612-70a008296fbe?w=400',
      region: null, seasons: ['winter'], occasions: [O.muharram, O['eid-ul-fitr']],
      mealType: 'lunch', prepTimeMinutes: 180, servings: 8, tags: ['meat', 'festive'],
      ingredients: [ing('Wheat', 'گندم', 0.5, 'cup'), ing('Lentils mix', 'دالیں', 1, 'cup'), ing('Beef', 'گوشت', 0.5, 'kg'), ing('Haleem masala', 'haleem مصالہ', 2, 'tbsp')],
      steps: [step('Soak grains and lentils overnight.', 'اناج رات بھر بھigoئیں۔'), step('Slow cook with beef until mushy.', 'گوشت کے ساتھ دھیمی آگ پر پکائیں۔'), step('Blend slightly and temper with fried onions.', 'ہلka blend کریں، پیاز تڑکا لگائیں۔')],
    },
    {
      nameEn: 'Mutton Pulao', nameUr: 'mutton pulao', imageUrl: 'https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?w=400',
      region: R.kpk, seasons: ['all'], occasions: [O['guest-visit'], O.wedding],
      mealType: 'lunch', prepTimeMinutes: 75, servings: 6, tags: ['meat', 'guest-friendly'],
      ingredients: [ing('Basmati rice', 'چاول', 0.5, 'kg'), ing('Mutton', 'بکرے کا گوشت', 0.5, 'kg'), ing('Onions', 'پیاز', 2, 'pcs'), ing('Whole spices', 'sabut مصالہ', 1, 'tbsp')],
      steps: [step('Cook mutton with onions and spices.', 'گوشت پیاز اور مصالے کے ساتھ پکائیں۔'), step('Add rice and stock, cook until done.', 'چاول اور yakhni ڈال کر پکائیں۔'), step('Rest 10 minutes before serving.', '10 منٹ rest دیں۔')],
    },
    {
      nameEn: 'Seekh Kebab', nameUr: 'seekh kebab', imageUrl: 'https://images.unsplash.com/photo-1529042410759-befb1204b468?w=400',
      region: null, seasons: ['all'], occasions: [O['guest-visit'], O['eid-ul-adha']],
      mealType: 'dinner', prepTimeMinutes: 35, servings: 4, tags: ['meat', 'quick', 'guest-friendly'],
      ingredients: [ing('Minced beef', 'قیمہ', 0.5, 'kg'), ing('Onion', 'پیاز', 1, 'pcs'), ing('Seekh masala', 'kebab مصالہ', 2, 'tbsp'), ing('Coriander', 'دھنیا', 2, 'tbsp')],
      steps: [step('Mix mince with spices.', 'قیمہ مصالے کے ساتھ ملا لیں۔'), step('Shape on skewers.', 'سیخ پر لگائیں۔'), step('Grill or barbecue until done.', 'grill یا barbecue کریں۔')],
    },
    {
      nameEn: 'Aloo Gosht', nameUr: 'آلو گوشت', imageUrl: 'https://images.unsplash.com/photo-1603894584373-5ac82b2ae398?w=400',
      region: null, seasons: ['all'], occasions: [],
      mealType: 'lunch', prepTimeMinutes: 50, servings: 4, tags: ['meat'],
      ingredients: [ing('Mutton', 'گوشت', 0.5, 'kg'), ing('Potatoes', 'آلو', 3, 'pcs'), ing('Onion', 'پیاز', 1, 'pcs'), ing('Tomato', 'ٹماٹر', 2, 'pcs'), ing('Ginger garlic', 'adrak lehsan', 1, 'tbsp')],
      steps: [step('Fry onion until golden.', 'پیاز سنہری بھونیں۔'), step('Add meat and cook until tender.', 'گوشت نرم پکائیں۔'), step('Add potatoes and tomatoes, simmer.', 'آلو اور ٹماٹر ڈال کر دم دیں۔')],
    },
    {
      nameEn: 'Kashmiri Chai', nameUr: 'kashmiri chai', imageUrl: 'https://images.unsplash.com/photo-1576092768241-dec231879fc3?w=400',
      region: R['gilgit-baltistan'], seasons: ['winter', 'monsoon'], occasions: [],
      mealType: 'drink', prepTimeMinutes: 20, servings: 4, tags: ['veg', 'quick'],
      ingredients: [ing('Green tea leaves', 'green chai', 2, 'tbsp'), ing('Baking soda', 'soda', 0.25, 'tsp'), ing('Milk', 'doodh', 2, 'cup'), ing('Salt', 'namak', 0.5, 'tsp'), ing('Almonds', 'badam', 2, 'tbsp')],
      steps: [step('Boil tea leaves with soda until pink.', 'chai aur soda se gulabi rang laen.'), step('Add milk and salt.', 'doodh aur namak dalein.'), step('Simmer and garnish with almonds.', 'badam se sajha kar pesh karein.')],
    },
    {
      nameEn: 'Anda Paratha', nameUr: 'anda paratha', imageUrl: 'https://images.unsplash.com/photo-1601050690597-df0568fa7098?w=400',
      region: null, seasons: ['all'], occasions: [O.sehri],
      mealType: 'breakfast', prepTimeMinutes: 15, servings: 2, tags: ['meat', 'quick'],
      ingredients: [ing('Eggs', 'anday', 2, 'pcs'), ing('Paratha', 'paratha', 2, 'pcs'), ing('Butter', 'makhan', 2, 'tbsp'), ing('Salt', 'namak', 0.5, 'tsp')],
      steps: [step('Beat eggs with salt.', 'anday phaintein.'), step('Pour on paratha on tawa.', 'taway par paratha par anday dalein.'), step('Fold and cook both sides.', 'dono taraf seka kar garam pesh karein.')],
    },
    {
      nameEn: 'Korma', nameUr: 'qorma', imageUrl: 'https://images.unsplash.com/photo-1603894584373-5ac82b2ae398?w=400',
      region: R.punjab, seasons: ['all'], occasions: [O['eid-ul-fitr'], O.wedding],
      mealType: 'lunch', prepTimeMinutes: 60, servings: 6, tags: ['meat', 'festive', 'guest-friendly'],
      ingredients: [ing('Chicken', 'murghi', 1, 'kg'), ing('Yogurt', 'dahi', 1, 'cup'), ing('Fried onions', 'talay pyaz', 1, 'cup'), ing('Korma masala', 'qorma masala', 2, 'tbsp')],
      steps: [step('Fry chicken with korma masala.', 'murghi masalay ke sath bhoonain.'), step('Add yogurt and fried onions.', 'dahi aur pyaz dalein.'), step('Slow cook until oil separates.', 'dheemi aanch par pakayen.')],
    },
    {
      nameEn: 'Sai Bhaji', nameUr: 'sai bhaji', imageUrl: 'https://images.unsplash.com/photo-1546833999-b9f581a1996d?w=400',
      region: R.sindh, seasons: ['winter', 'spring'], occasions: [],
      mealType: 'lunch', prepTimeMinutes: 45, servings: 4, tags: ['veg'],
      ingredients: [ing('Spinach', 'palak', 0.5, 'kg'), ing('Chana daal', 'chanay ki dal', 0.5, 'cup'), ing('Vegetables mix', 'sabziyan', 2, 'cup'), ing('Tomatoes', 'tamatar', 2, 'pcs')],
      steps: [step('Cook daal until soft.', 'dal naram pakayen.'), step('Add chopped vegetables and spinach.', 'sabziyan aur palak dalein.'), step('Simmer until thick, serve with rice.', 'gaarha kar chawal ke sath pesh karein.')],
    },
    {
      nameEn: 'Peshawari Karahi', nameUr: 'peshawari karahi', imageUrl: 'https://images.unsplash.com/photo-1603894584373-5ac82b2ae398?w=400',
      region: R.kpk, seasons: ['all'], occasions: [O['guest-visit']],
      mealType: 'dinner', prepTimeMinutes: 40, servings: 4, tags: ['meat', 'guest-friendly'],
      ingredients: [ing('Lamb', 'gosht', 0.75, 'kg'), ing('Tomatoes', 'tamatar', 5, 'pcs'), ing('Green chilies', 'hari mirch', 6, 'pcs'), ing('Coriander', 'dhania', 3, 'tbsp')],
      steps: [step('Cook lamb in its own fat.', 'gosht apni charbi mein pakayen.'), step('Add tomatoes and chilies.', 'tamatar aur mirch dalein.'), step('Finish with fresh coriander.', 'taza dhania se garnish karein.')],
    },
    {
      nameEn: 'BBQ Tikka', nameUr: 'tikka boti', imageUrl: 'https://images.unsplash.com/photo-1529042410759-befb1204b468?w=400',
      region: null, seasons: ['all'], occasions: [O['eid-ul-adha'], O['guest-visit']],
      mealType: 'dinner', prepTimeMinutes: 50, servings: 4, tags: ['meat', 'guest-friendly'],
      ingredients: [ing('Chicken pieces', 'murghi', 1, 'kg'), ing('Yogurt', 'dahi', 1, 'cup'), ing('Tikka masala', 'tikka masala', 2, 'tbsp'), ing('Lemon', 'leemoon', 2, 'pcs')],
      steps: [step('Marinate chicken 2 hours.', 'murghi 2 ghantay marinate karein.'), step('Skewer and grill.', 'seekh par grill karein.'), step('Serve with raita and naan.', 'raita aur naan ke sath pesh karein.')],
    },
    {
      nameEn: 'Kaleji Fry', nameUr: 'kaleji fry', imageUrl: 'https://images.unsplash.com/photo-1603894584373-5ac82b2ae398?w=400',
      region: null, seasons: ['all'], occasions: [O['eid-ul-adha']],
      mealType: 'breakfast', prepTimeMinutes: 30, servings: 4, tags: ['meat', 'quick'],
      ingredients: [ing('Liver', 'kaleji', 0.5, 'kg'), ing('Onion', 'pyaz', 2, 'pcs'), ing('Green chilies', 'hari mirch', 4, 'pcs'), ing('Ginger garlic', 'adrak lehsan', 1, 'tbsp')],
      steps: [step('Clean and slice liver.', 'kaleji saaf kar kaat lein.'), step('Fry with onions on high heat quickly.', 'tez aanch par jaldi bhoon lein.'), step('Do not overcook.', 'zyada na pakayen warna sakht ho jati hai.')],
    },
    {
      nameEn: 'Paya', nameUr: 'paya', imageUrl: 'https://images.unsplash.com/photo-1585937421612-70a008296fbe?w=400',
      region: R.punjab, seasons: ['winter'], occasions: [O['eid-ul-adha']],
      mealType: 'breakfast', prepTimeMinutes: 240, servings: 6, tags: ['meat'],
      ingredients: [ing('Goat trotters', 'paya', 4, 'pcs'), ing('Wheat flour', 'atta', 2, 'tbsp'), ing('Ginger garlic', 'adrak lehsan', 2, 'tbsp'), ing('Spices', 'garam masala', 1, 'tbsp')],
      steps: [step('Pressure cook paya overnight or 4 hours.', 'paya raat bhar ya 4 ghantay pakayen.'), step('Add flour slurry to thicken.', 'atta mila kar gaarha karein.'), step('Serve with naan for breakfast.', 'naan ke sath nashte mein pesh karein.')],
    },
    {
      nameEn: 'Samosa', nameUr: 'samosa', imageUrl: 'https://images.unsplash.com/photo-1606491956689-2ea866880f84?w=400',
      region: null, seasons: ['monsoon'], occasions: [O['ramadan-iftar']],
      mealType: 'snack', prepTimeMinutes: 45, servings: 6, tags: ['veg'],
      ingredients: [ing('Samosa sheets', 'samosa patti', 12, 'pcs'), ing('Potatoes', 'aloo', 3, 'pcs'), ing('Peas', 'matar', 0.5, 'cup'), ing('Cumin', 'zeera', 1, 'tsp')],
      steps: [step('Make spiced potato filling.', 'aloo ki bhujia tayyar karein.'), step('Fill and fold samosas.', 'samosa bharein aur lapet lein.'), step('Deep fry until crispy.', 'khasta hone tak tal lein.')],
    },
    {
      nameEn: 'Zarda', nameUr: 'zarda', imageUrl: 'https://images.unsplash.com/photo-1488477181946-6428a0291777?w=400',
      region: null, seasons: ['all'], occasions: [O.wedding, O.basant],
      mealType: 'dessert', prepTimeMinutes: 45, servings: 8, tags: ['veg', 'festive'],
      ingredients: [ing('Basmati rice', 'chawal', 1, 'cup'), ing('Sugar', 'cheeni', 1, 'cup'), ing('Yellow color', 'zard rang', 0.25, 'tsp'), ing('Dry fruits', 'dry fruits', 0.5, 'cup')],
      steps: [step('Boil rice with color until done.', 'rang ke sath chawal pakayen.'), step('Layer with sugar and dry fruits.', 'cheeni aur dry fruits ki tah lagayen.'), step('Dum on low heat 15 minutes.', '15 min dum dein.')],
    },
    {
      nameEn: 'Khichra', nameUr: 'khichra', imageUrl: 'https://images.unsplash.com/photo-1585937421612-70a008296fbe?w=400',
      region: null, seasons: ['winter'], occasions: [O.muharram],
      mealType: 'lunch', prepTimeMinutes: 200, servings: 8, tags: ['meat', 'festive'],
      ingredients: [ing('Wheat', 'gandum', 0.5, 'cup'), ing('Lentils', 'dalain', 1, 'cup'), ing('Beef', 'gosht', 0.5, 'kg'), ing('Spices', 'masala', 2, 'tbsp')],
      steps: [step('Slow cook all ingredients together.', 'sab cheezain sath dheemi aanch par pakayen.'), step('Stir until thick and blended.', 'gaarha ho jane tak hilatay rahein.'), step('Serve with lemon and ginger.', 'leemoon aur adrak ke sath pesh karein.')],
    },
    {
      nameEn: 'Chana Chaat', nameUr: 'chana chaat', imageUrl: 'https://images.unsplash.com/photo-1564093497595-5931221260e7?w=400',
      region: null, seasons: ['summer'], occasions: [O['ramadan-iftar']],
      mealType: 'snack', prepTimeMinutes: 20, servings: 4, tags: ['veg', 'quick'],
      ingredients: [ing('Chickpeas', 'chanay', 2, 'cup'), ing('Onion', 'pyaz', 1, 'pcs'), ing('Tomato', 'tamatar', 1, 'pcs'), ing('Chaat masala', 'chaat masala', 1, 'tbsp'), ing('Tamarind', 'imli', 2, 'tbsp')],
      steps: [step('Boil chickpeas until soft.', 'chanay naram pakayen.'), step('Mix with chopped vegetables.', 'sabziyan mila lein.'), step('Add chaat masala and imli.', 'masala aur imli dalein.')],
    },
    {
      nameEn: 'Aam Panna', nameUr: 'aam panna', imageUrl: 'https://images.unsplash.com/photo-1626074353765-517a5e3a7969?w=400',
      region: null, seasons: ['summer'], occasions: [],
      mealType: 'drink', prepTimeMinutes: 20, servings: 4, tags: ['veg', 'quick'],
      ingredients: [ing('Raw mango', 'kacha aam', 2, 'pcs'), ing('Sugar', 'cheeni', 0.5, 'cup'), ing('Cumin', 'zeera', 1, 'tsp'), ing('Mint', 'podina', 10, 'leaves')],
      steps: [step('Boil and pulp raw mangoes.', 'aam ka pulp nikaalein.'), step('Blend with sugar, cumin and mint.', 'cheeni zeera podina ke sath blend karein.'), step('Serve chilled with ice.', 'barf ke sath thanda pesh karein.')],
    },
    {
      nameEn: 'Bhindi Gosht', nameUr: 'bhindi gosht', imageUrl: 'https://images.unsplash.com/photo-1603894584373-5ac82b2ae398?w=400',
      region: R.sindh, seasons: ['summer'], occasions: [],
      mealType: 'lunch', prepTimeMinutes: 45, servings: 4, tags: ['meat'],
      ingredients: [ing('Okra', 'bhindi', 0.5, 'kg'), ing('Mutton', 'gosht', 0.5, 'kg'), ing('Onion', 'pyaz', 1, 'pcs'), ing('Tomatoes', 'tamatar', 2, 'pcs')],
      steps: [step('Fry okra separately.', 'bhindi alag bhoon lein.'), step('Cook meat with onions and tomatoes.', 'gosht pyaz tamatar ke sath pakayen.'), step('Combine and simmer 10 minutes.', 'milaa kar 10 min dum dein.')],
    },
    {
      nameEn: 'Daal Makhani', nameUr: 'daal makhani', imageUrl: 'https://images.unsplash.com/photo-1512058564366-18510be2db19?w=400',
      region: R.punjab, seasons: ['winter'], occasions: [O['guest-visit']],
      mealType: 'lunch', prepTimeMinutes: 90, servings: 6, tags: ['veg', 'guest-friendly'],
      ingredients: [ing('Black urad daal', 'kali urad', 1, 'cup'), ing('Kidney beans', 'lobia', 0.5, 'cup'), ing('Butter', 'makhan', 4, 'tbsp'), ing('Cream', 'cream', 0.25, 'cup')],
      steps: [step('Soak daal and beans overnight.', 'raat bhar bhigoyen.'), step('Slow cook until creamy.', 'dheemi aanch par creamy pakayen.'), step('Finish with butter and cream.', 'makhan aur cream se finish karein.')],
    },
    {
      nameEn: 'Chicken Biryani', nameUr: 'chicken biryani', imageUrl: 'https://images.unsplash.com/photo-1563379091335-03b21ab4a4f8?w=400',
      region: null, seasons: ['all'], occasions: [O['eid-ul-fitr'], O.birthday, O['guest-visit']],
      mealType: 'lunch', prepTimeMinutes: 75, servings: 6, tags: ['meat', 'festive', 'guest-friendly'],
      ingredients: [ing('Chicken', 'murghi', 1, 'kg'), ing('Basmati rice', 'chawal', 0.5, 'kg'), ing('Yogurt', 'dahi', 1, 'cup'), ing('Biryani masala', 'biryani masala', 2, 'tbsp')],
      steps: [step('Marinate chicken with yogurt and masala.', 'murghi marinate karein.'), step('Parboil rice.', 'chawal adha pakayen.'), step('Layer and dum cook 25 minutes.', 'tah laga kar 25 min dum dein.')],
    },
    {
      nameEn: 'Raita', nameUr: 'raita', imageUrl: 'https://images.unsplash.com/photo-1626074353765-517a5e3a7969?w=400',
      region: null, seasons: ['summer'], occasions: [O['guest-visit']],
      mealType: 'snack', prepTimeMinutes: 10, servings: 4, tags: ['veg', 'quick'],
      ingredients: [ing('Yogurt', 'dahi', 2, 'cup'), ing('Cucumber', 'kheera', 1, 'pcs'), ing('Salt', 'namak', 0.5, 'tsp'), ing('Cumin', 'bhuna zeera', 0.5, 'tsp')],
      steps: [step('Whisk yogurt smooth.', 'dahi phaintein.'), step('Add grated cucumber and spices.', 'kheera aur masala dalein.'), step('Serve chilled with biryani.', 'thanda biryani ke sath pesh karein.')],
    },
    {
      nameEn: 'Halwa Puri', nameUr: 'halwa puri', imageUrl: 'https://images.unsplash.com/photo-1488477181946-6428a0291777?w=400',
      region: R.punjab, seasons: ['all'], occasions: [O['eid-ul-fitr']],
      mealType: 'breakfast', prepTimeMinutes: 60, servings: 4, tags: ['veg', 'festive'],
      ingredients: [ing('Semolina', 'suji', 1, 'cup'), ing('Sugar', 'cheeni', 1, 'cup'), ing('Flour', 'maida', 2, 'cup'), ing('Ghee', 'ghee', 0.5, 'cup')],
      steps: [step('Make sooji halwa.', 'suji ka halwa banayen.'), step('Make puri dough and fry.', 'puri tal lein.'), step('Serve halwa with hot puris.', 'garam puri ke sath halwa pesh karein.')],
    },
    {
      nameEn: 'Chai', nameUr: 'doodh patti', imageUrl: 'https://images.unsplash.com/photo-1576092768241-dec231879fc3?w=400',
      region: null, seasons: ['all'], occasions: [O.sehri],
      mealType: 'drink', prepTimeMinutes: 10, servings: 2, tags: ['veg', 'quick'],
      ingredients: [ing('Tea leaves', 'patti', 2, 'tsp'), ing('Milk', 'doodh', 1.5, 'cup'), ing('Sugar', 'cheeni', 2, 'tbsp'), ing('Water', 'pani', 0.5, 'cup')],
      steps: [step('Boil water with tea leaves.', 'pani mein patti ubalein.'), step('Add milk and sugar, simmer.', 'doodh aur cheeni dalein.'), step('Strain and serve hot.', 'garam pesh karein.')],
    },
    {
      nameEn: 'Shami Kebab', nameUr: 'shami kebab', imageUrl: 'https://images.unsplash.com/photo-1529042410759-befb1204b468?w=400',
      region: null, seasons: ['all'], occasions: [O['guest-visit']],
      mealType: 'snack', prepTimeMinutes: 50, servings: 6, tags: ['meat', 'guest-friendly'],
      ingredients: [ing('Beef mince', 'qeema', 0.5, 'kg'), ing('Chana daal', 'chanay ki dal', 0.5, 'cup'), ing('Egg', 'anda', 1, 'pcs'), ing('Spices', 'masala', 2, 'tbsp')],
      steps: [step('Cook mince and daal together until dry.', 'qeema aur dal sukha lein.'), step('Grind to smooth paste.', 'bareek pees lein.'), step('Shape patties, dip in egg and shallow fry.', 'anday mein dubo kar tal lein.')],
    },
    {
      nameEn: 'Mixed Vegetable Curry', nameUr: 'mix sabzi', imageUrl: 'https://images.unsplash.com/photo-1546833999-b9f581a1996d?w=400',
      region: null, seasons: ['spring', 'summer'], occasions: [],
      mealType: 'lunch', prepTimeMinutes: 30, servings: 4, tags: ['veg', 'quick'],
      ingredients: [ing('Mixed vegetables', 'sabziyan', 4, 'cup'), ing('Onion', 'pyaz', 1, 'pcs'), ing('Tomato', 'tamatar', 2, 'pcs'), ing('Turmeric', 'haldi', 0.5, 'tsp')],
      steps: [step('Saute onion and tomato.', 'pyaz tamatar bhoon lein.'), step('Add vegetables and spices.', 'sabziyan aur masala dalein.'), step('Cover and cook until tender.', 'dhak kar naram pakayen.')],
    },
    {
      nameEn: 'Keema Paratha', nameUr: 'qeema paratha', imageUrl: 'https://images.unsplash.com/photo-1601050690597-df0568fa7098?w=400',
      region: R.punjab, seasons: ['all'], occasions: [O.sehri],
      mealType: 'breakfast', prepTimeMinutes: 35, servings: 4, tags: ['meat'],
      ingredients: [ing('Minced beef', 'qeema', 0.25, 'kg'), ing('Wheat flour', 'atta', 2, 'cup'), ing('Onion', 'pyaz', 1, 'pcs'), ing('Green chilies', 'hari mirch', 2, 'pcs')],
      steps: [step('Cook spiced keema until dry.', 'qeema bhoon lein.'), step('Stuff in paratha dough.', 'paratha mein bharein.'), step('Cook on tawa with ghee.', 'ghee mein sek lein.')],
    },
    {
      nameEn: 'Kheer', nameUr: 'kheer', imageUrl: 'https://images.unsplash.com/photo-1488477181946-6428a0291777?w=400',
      region: null, seasons: ['all'], occasions: [O['eid-ul-fitr'], O.birthday],
      mealType: 'dessert', prepTimeMinutes: 45, servings: 6, tags: ['veg', 'festive'],
      ingredients: [ing('Rice', 'chawal', 0.25, 'cup'), ing('Milk', 'doodh', 1, 'litre'), ing('Sugar', 'cheeni', 0.5, 'cup'), ing('Cardamom', 'elaichi', 4, 'pcs')],
      steps: [step('Boil milk with rice on low heat.', 'doodh mein chawal pakayen.'), step('Stir until thick and creamy.', 'gaarha hone tak hilayen.'), step('Add sugar and cardamom.', 'cheeni aur elaichi dalein.')],
    },
    {
      nameEn: 'Murgh Cholay', nameUr: 'murgh cholay', imageUrl: 'https://images.unsplash.com/photo-1603894584373-5ac82b2ae398?w=400',
      region: R.punjab, seasons: ['winter'], occasions: [],
      mealType: 'lunch', prepTimeMinutes: 55, servings: 4, tags: ['meat'],
      ingredients: [ing('Chicken', 'murghi', 0.5, 'kg'), ing('Chickpeas', 'cholay', 1, 'cup'), ing('Onion', 'pyaz', 1, 'pcs'), ing('Chana masala', 'chana masala', 2, 'tbsp')],
      steps: [step('Boil chickpeas until soft.', 'cholay pakayen.'), step('Cook chicken with masala.', 'murghi masalay ke sath pakayen.'), step('Combine and simmer.', 'milaa kar dum dein.')],
    },
    {
      nameEn: 'Fish Karahi', nameUr: 'machli karahi', imageUrl: 'https://images.unsplash.com/photo-1603894584373-5ac82b2ae398?w=400',
      region: R.sindh, seasons: ['winter'], occasions: [O['guest-visit']],
      mealType: 'dinner', prepTimeMinutes: 30, servings: 4, tags: ['meat', 'quick', 'guest-friendly'],
      ingredients: [ing('Fish fillets', 'machli', 0.5, 'kg'), ing('Tomatoes', 'tamatar', 3, 'pcs'), ing('Green chilies', 'hari mirch', 4, 'pcs'), ing('Ginger garlic', 'adrak lehsan', 1, 'tbsp')],
      steps: [step('Lightly fry fish pieces.', 'machli halka tal lein.'), step('Make tomato karahi masala.', 'tamatar ki karahi tayyar karein.'), step('Add fish gently and simmer 5 minutes.', 'machli dalein aur 5 min pakayen.')],
    },
    {
      nameEn: 'Pulao', nameUr: 'pulao', imageUrl: 'https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?w=400',
      region: null, seasons: ['all'], occasions: [O['guest-visit']],
      mealType: 'lunch', prepTimeMinutes: 40, servings: 4, tags: ['meat', 'quick', 'guest-friendly'],
      ingredients: [ing('Basmati rice', 'chawal', 2, 'cup'), ing('Chicken', 'murghi', 0.5, 'kg'), ing('Whole spices', 'sabut masala', 1, 'tbsp'), ing('Onion', 'pyaz', 1, 'pcs')],
      steps: [step('Fry onion and whole spices.', 'pyaz aur masala bhoon lein.'), step('Add chicken and rice with water.', 'murghi aur chawal dalein.'), step('Cook until rice is fluffy.', 'chawal khula pakayen.')],
    },
    {
      nameEn: 'Khajoor Shake', nameUr: 'khajoor shake', imageUrl: 'https://images.unsplash.com/photo-1626074353765-517a5e3a7969?w=400',
      region: null, seasons: ['summer'], occasions: [O['ramadan-iftar']],
      mealType: 'drink', prepTimeMinutes: 10, servings: 2, tags: ['veg', 'quick'],
      ingredients: [ing('Dates', 'khajoor', 8, 'pcs'), ing('Milk', 'doodh', 2, 'cup'), ing('Ice', 'barf', 1, 'cup'), ing('Honey', 'shahad', 1, 'tbsp')],
      steps: [step('Remove seeds from dates.', 'guthli nikaal lein.'), step('Blend with milk, ice and honey.', 'doodh barf aur shahad ke sath blend karein.'), step('Serve immediately.', 'foran pesh karein.')],
    },
    {
      nameEn: 'Palak Gosht', nameUr: 'palak gosht', imageUrl: 'https://images.unsplash.com/photo-1603894584373-5ac82b2ae398?w=400',
      region: null, seasons: ['winter'], occasions: [],
      mealType: 'lunch', prepTimeMinutes: 45, servings: 4, tags: ['meat'],
      ingredients: [ing('Spinach', 'palak', 0.5, 'kg'), ing('Mutton', 'gosht', 0.5, 'kg'), ing('Onion', 'pyaz', 1, 'pcs'), ing('Green chilies', 'hari mirch', 3, 'pcs')],
      steps: [step('Cook meat until tender.', 'gosht naram pakayen.'), step('Add chopped spinach.', 'kata palak dalein.'), step('Simmer until spinach wilts.', 'palak gal jane tak pakayen.')],
    },
    {
      nameEn: 'Jalebi', nameUr: 'jalebi', imageUrl: 'https://images.unsplash.com/photo-1488477181946-6428a0291777?w=400',
      region: null, seasons: ['all'], occasions: [O['eid-ul-fitr'], O.basant],
      mealType: 'dessert', prepTimeMinutes: 40, servings: 6, tags: ['veg', 'festive'],
      ingredients: [ing('Flour', 'maida', 1, 'cup'), ing('Yogurt', 'dahi', 2, 'tbsp'), ing('Sugar syrup', 'sheera', 2, 'cup'), ing('Food color', 'rang', 2, 'drops')],
      steps: [step('Make fermented batter.', 'khameer wala batter banayen.'), step('Pipe into hot oil in circles.', 'tel mein gol shape mein dalein.'), step('Dip in warm sugar syrup.', 'garam sheere mein dubo lein.')],
    },
    {
      nameEn: 'Tandoori Naan', nameUr: 'naan', imageUrl: 'https://images.unsplash.com/photo-1601050690597-df0568fa7098?w=400',
      region: null, seasons: ['all'], occasions: [O['guest-visit']],
      mealType: 'snack', prepTimeMinutes: 30, servings: 4, tags: ['veg', 'quick'],
      ingredients: [ing('Flour', 'maida', 2, 'cup'), ing('Yogurt', 'dahi', 3, 'tbsp'), ing('Yeast', 'khameer', 1, 'tsp'), ing('Butter', 'makhan', 2, 'tbsp')],
      steps: [step('Knead soft dough with yeast.', 'naram atta gundh lein.'), step('Roll naan shapes.', 'naan bana lein.'), step('Bake on tawa or oven, brush butter.', 'sek kar makhan laga lein.')],
    },
    {
      nameEn: 'Egg Curry', nameUr: 'anday ka salan', imageUrl: 'https://images.unsplash.com/photo-1603894584373-5ac82b2ae398?w=400',
      region: null, seasons: ['all'], occasions: [],
      mealType: 'lunch', prepTimeMinutes: 25, servings: 4, tags: ['meat', 'quick'],
      ingredients: [ing('Eggs', 'anday', 6, 'pcs'), ing('Onion', 'pyaz', 1, 'pcs'), ing('Tomato', 'tamatar', 2, 'pcs'), ing('Red chili', 'lal mirch', 1, 'tsp')],
      steps: [step('Boil and peel eggs.', 'anday ubalein.'), step('Make onion tomato curry base.', 'pyaz tamatar ka salan banayen.'), step('Add halved eggs and simmer.', 'anday dalein aur dum dein.')],
    },
    {
      nameEn: 'Bhuna Gosht', nameUr: 'bhuna gosht', imageUrl: 'https://images.unsplash.com/photo-1603894584373-5ac82b2ae398?w=400',
      region: R.punjab, seasons: ['all'], occasions: [O['guest-visit']],
      mealType: 'dinner', prepTimeMinutes: 70, servings: 4, tags: ['meat', 'guest-friendly'],
      ingredients: [ing('Beef', 'gosht', 0.75, 'kg'), ing('Onions', 'pyaz', 3, 'pcs'), ing('Yogurt', 'dahi', 0.5, 'cup'), ing('Ginger garlic', 'adrak lehsan', 2, 'tbsp')],
      steps: [step('Slow cook meat with onions until dry.', 'pyaz ke sath sukha bhoon lein.'), step('Add yogurt and spices.', 'dahi aur masala dalein.'), step('Cook until oil separates.', 'tale alag hone tak pakayen.')],
    },
    ...buildExtraRecipes(R, O, ing, step),
  ];
}
